export const enum ConstructType {
  Component = 'component',
  Service = 'service',
  Pipe = 'pipe',
  Directive = 'directive',
  Module = 'module',
  Guard = 'guard',
  Interceptor = 'interceptor',
  Interface = 'interface',
  Enum = 'enum',
  Resolver = 'resolver',
  Library = 'library',
  Config = 'config',
  Environments = 'environments',
}
